apiVersion: v1  #无头服务创建StatefulSet 前必须先新建无头服务
kind: Service 
metadata: 
  name: nginx 
  labels: 
    app: nginx 
spec: 
  ports: 
  - port: 80 
    name: web 
  clusterIP: None 
  selector: 
    app: nginx
--- 
apiVersion: apps/v1 
kind: StatefulSet  #控制器StatefulSet为
metadata: 
  name: web 
spec: 
  selector: 
    matchLabels: 
      app: nginx 
  serviceName: "nginx" 
  replicas: 3 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx-test 
        image: nginx
        ports: 
        - containerPort: 80 
          name: web 
        volumeMounts: 
        - name: www 
          mountPath: /usr/share/nginx/html 
  volumeClaimTemplates: 
  - metadata: 
      name: www 
    spec: 
      accessModes: [ "ReadWriteOnce" ] #必须和pv一致
      storageClassName: "slow"  #必须和pv一致
      resources:
          requests: 
            storage: 1Gi
