apiVersion: v1 
kind: Service 
metadata: 
  name: myapp #标签1
  namespace: default #标签2     标签1标签2 找到对应的deployment
spec: 
  type: ClusterIP 
  selector: 
    app: myapp 
    release: stabel 
  ports: 
  - name: http 
    port: 80 
    targetPort: 80
