apiVersion: v1 
kind: Pod 
metadata: 
   name: probe-tcp 
spec: 
   containers: 
   - name: ng 
     image: nginx 
     livenessProbe: 
       initialDelaySeconds: 5 
       timeoutSeconds: 1 
       tcpSocket: 
         port: 8080
       periodSeconds: 3 #周期
