
apiVersion: v1
kind: Pod
metadata:
   name: liveness-httpget-pod
   namespace: default
spec:
  containers:
  - name: liveness-httpget-container
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    readinessProbe: #准备情况探针 就绪检测
      httpGet: 
          port: 80 
          path: /index1.html 
      initialDelaySeconds: 1  #延迟时间
      periodSeconds: 3 #周期时间
    livenessProbe: #存活检测
         httpGet:
            port: http
            path: /index.html
         initialDelaySeconds: 1
         periodSeconds: 3
         timeoutSeconds: 10

