apiVersion: v1 
kind: Pod 
metadata: 
  name: dapi-test-pod11 
spec: 
  containers: 
  - name: test-container 
    image: nginx
    command: [ "/bin/sh", "-c", "sleep 600s" ] 
    volumeMounts: #表示对容器挂载
    - name: config-volume #对应配置挂载名称 
      mountPath: /etc/config #挂载路径
  volumes: #定义挂载
  - name: config-volume #卷名称
    configMap: #卷获取配置
      name: special-config #从special-config configmap中导入
  restartPolicy: Never #从不重启

