apiVersion: v1 
kind: Pod 
metadata: 
  name: dapi-test-pod 
spec: 
  containers: 
  - name: test-container 
    image: nginx 
    command: [ "/bin/sh", "-c", "sleep 600 s" ] # 运行命令打印env 
    env: #另一种导入方式
    - name: SPECIAL_LEVEL_KEY #键名 
      valueFrom: 
        configMapKeyRef: 
          name: special-config #configmap名称
          key: special.how #configmap里的键名将值赋给 SPECIAL_LEVEL_KEY
    - name: SPECIAL_TYPE_KEY 
      valueFrom: 
        configMapKeyRef:
         name: special-config 
         key: special.type 
    envFrom: #env从哪里来 configmap的一种导入方式
     - configMapRef: 
         name: env-config 
  restartPolicy: Never

